/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.gearrent.view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishara
 */
public class CustomerView extends javax.swing.JFrame {
    
    public JTable tblCustomers;
    public JTextField txtName, txtNIC, txtContact, txtEmail, txtAddress;
    public JButton btnAdd, btnUpdate, btnClear;

    public CustomerView() {

        setTitle("Customer Management");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setLayout(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        JLabel lblName = new JLabel("Name");
        lblName.setBounds(30, 30, 100, 25);
        add(lblName);

        txtName = new JTextField();
        txtName.setBounds(120, 30, 200, 25);
        add(txtName);

        JLabel lblNIC = new JLabel("NIC / Passport");
        lblNIC.setBounds(30, 70, 100, 25);
        add(lblNIC);

        txtNIC = new JTextField();
        txtNIC.setBounds(120, 70, 200, 25);
        add(txtNIC);

        JLabel lblContact = new JLabel("Contact");
        lblContact.setBounds(30, 110, 100, 25);
        add(lblContact);

        txtContact = new JTextField();
        txtContact.setBounds(120, 110, 200, 25);
        add(txtContact);

        JLabel lblEmail = new JLabel("Email");
        lblEmail.setBounds(30, 150, 100, 25);
        add(lblEmail);

        txtEmail = new JTextField();
        txtEmail.setBounds(120, 150, 200, 25);
        add(txtEmail);

        JLabel lblAddress = new JLabel("Address");
        lblAddress.setBounds(30, 190, 100, 25);
        add(lblAddress);

        txtAddress = new JTextField();
        txtAddress.setBounds(120, 190, 200, 25);
        add(txtAddress);

        btnAdd = new JButton("Add");
        btnAdd.setBounds(50, 240, 120, 30);
        add(btnAdd);

        btnUpdate = new JButton("Update");
        btnUpdate.setBounds(190, 240, 120, 30);
        add(btnUpdate);

        btnClear = new JButton("Clear");
        btnClear.setBounds(120, 280, 120, 30);
        add(btnClear);

        tblCustomers = new JTable(new DefaultTableModel(
                new Object[]{"ID", "Name", "NIC", "Contact", "Email", "Address"},
                0
        ));
        JScrollPane scrollPane = new JScrollPane(tblCustomers);
        scrollPane.setBounds(350, 30, 420, 350);
        add(scrollPane);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerView.class.getName());

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
