/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.gearrent.view;

import com.ijse.gearrent.dto.UserDto;

import javax.swing.*;

/**
 *
 * @author Ishara
 */
public class DashboardView extends JFrame {

   
    public JButton btnCustomers;
    public JButton btnEquipment;
    public JButton btnRental;
    public JButton btnReservation;
    public JButton btnBranch;
    public JButton btnCategory;
    public JButton btnReturns;
    public JButton btnOverdue;

    public DashboardView() {
        setTitle("GearRent - Dashboard");
        setSize(600, 420);
        setLayout(null);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        btnCustomers = new JButton("Customers");
        btnEquipment = new JButton("Equipment");
        btnRental = new JButton("Rentals");
        btnReservation = new JButton("Reservations");
        btnBranch = new JButton("Branches");
        btnCategory = new JButton("Categories");
        btnReturns = new JButton("Returns");
        btnOverdue = new JButton("Overdue Rentals");

        btnCustomers.setBounds(50, 40, 200, 40);
        btnEquipment.setBounds(300, 40, 200, 40);
        btnRental.setBounds(50, 100, 200, 40);
        btnReservation.setBounds(300, 100, 200, 40);
        btnBranch.setBounds(50, 160, 200, 40);
        btnCategory.setBounds(300, 160, 200, 40);
        btnReturns.setBounds(50, 220, 200, 40);
        btnOverdue.setBounds(300, 220, 200, 40);

        add(btnCustomers);
        add(btnEquipment);
        add(btnRental);
        add(btnReservation);
        add(btnBranch);
        add(btnCategory);
        add(btnReturns);
        add(btnOverdue);
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView.class.getName());

    /**
     * Creates new form DashboardView
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
