/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.gearrent.view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishara
 */
public class EquipmentView extends javax.swing.JFrame {
    
  public JTable tblEquipment;

    public JTextField txtBrand;
    public JTextField txtModel;
    public JTextField txtPurchaseYear;
    public JTextField txtDailyPrice;
    public JTextField txtDeposit;

    public JComboBox<String> cmbStatus;
    public JComboBox<Integer> cmbCategoryId;

    public JButton btnAdd;
    public JButton btnUpdate;
    public JButton btnClear;

    public EquipmentView() {

        setTitle("Equipment Management");
        setSize(950, 500);
        setLocationRelativeTo(null);
        setLayout(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // ===== FORM =====
        JLabel lblBrand = new JLabel("Brand");
        lblBrand.setBounds(30, 30, 120, 25);
        add(lblBrand);

        txtBrand = new JTextField();
        txtBrand.setBounds(160, 30, 200, 25);
        add(txtBrand);

        JLabel lblModel = new JLabel("Model");
        lblModel.setBounds(30, 70, 120, 25);
        add(lblModel);

        txtModel = new JTextField();
        txtModel.setBounds(160, 70, 200, 25);
        add(txtModel);

        JLabel lblCategory = new JLabel("Category ID");
        lblCategory.setBounds(30, 110, 120, 25);
        add(lblCategory);

        cmbCategoryId = new JComboBox<>();
        cmbCategoryId.setBounds(160, 110, 200, 25);
        add(cmbCategoryId);

        JLabel lblYear = new JLabel("Purchase Year");
        lblYear.setBounds(30, 150, 120, 25);
        add(lblYear);

        txtPurchaseYear = new JTextField();
        txtPurchaseYear.setBounds(160, 150, 200, 25);
        add(txtPurchaseYear);

        JLabel lblPrice = new JLabel("Base Daily Price");
        lblPrice.setBounds(30, 190, 120, 25);
        add(lblPrice);

        txtDailyPrice = new JTextField();
        txtDailyPrice.setBounds(160, 190, 200, 25);
        add(txtDailyPrice);

        JLabel lblDeposit = new JLabel("Security Deposit");
        lblDeposit.setBounds(30, 230, 120, 25);
        add(lblDeposit);

        txtDeposit = new JTextField();
        txtDeposit.setBounds(160, 230, 200, 25);
        add(txtDeposit);

        JLabel lblStatus = new JLabel("Status");
        lblStatus.setBounds(30, 270, 120, 25);
        add(lblStatus);

        cmbStatus = new JComboBox<>(new String[]{
                "AVAILABLE", "RENTED", "MAINTENANCE"
        });
        cmbStatus.setBounds(160, 270, 200, 25);
        add(cmbStatus);

        btnAdd = new JButton("Add");
        btnAdd.setBounds(40, 320, 100, 30);
        add(btnAdd);

        btnUpdate = new JButton("Update");
        btnUpdate.setBounds(160, 320, 100, 30);
        add(btnUpdate);

        btnClear = new JButton("Clear");
        btnClear.setBounds(280, 320, 100, 30);
        add(btnClear);

        // ===== TABLE =====
        tblEquipment = new JTable(new DefaultTableModel(
                new Object[]{
                        "ID", "Category", "Brand", "Model",
                        "Year", "Daily Price", "Deposit", "Status"
                },
                0
        ));

        JScrollPane scroll = new JScrollPane(tblEquipment);
        scroll.setBounds(400, 30, 520, 350);
        add(scroll);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentView.class.getName());


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EquipmentView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
