/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.gearrent.view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishara
 */
public class RentalView extends javax.swing.JFrame {

    public JTable tblEquipment;

    public JTextField txtStartDate;
    public JTextField txtEndDate;
    public JTextField txtDays;
    public JTextField txtTotal;

    public JButton btnCheck;
    public JButton btnCalculate;
    public JButton btnClear;

    public RentalView() {

        setTitle("Rental Management");
        setSize(900, 500);
        setLocationRelativeTo(null);
        setLayout(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        JLabel lblStart = new JLabel("Start Date (YYYY-MM-DD)");
        lblStart.setBounds(30, 30, 200, 25);
        add(lblStart);

        txtStartDate = new JTextField();
        txtStartDate.setBounds(240, 30, 150, 25);
        add(txtStartDate);

        JLabel lblEnd = new JLabel("End Date (YYYY-MM-DD)");
        lblEnd.setBounds(30, 70, 200, 25);
        add(lblEnd);

        txtEndDate = new JTextField();
        txtEndDate.setBounds(240, 70, 150, 25);
        add(txtEndDate);

        btnCheck = new JButton("Check Available Equipment");
        btnCheck.setBounds(30, 110, 360, 30);
        add(btnCheck);

        tblEquipment = new JTable(new DefaultTableModel(
                new Object[]{
                        "ID", "Brand", "Model",
                        "Daily Price", "Deposit", "Status"
                },
                0
        ));

        JScrollPane scrollPane = new JScrollPane(tblEquipment);
        scrollPane.setBounds(420, 30, 440, 300);
        add(scrollPane);

        JLabel lblDays = new JLabel("No of Days");
        lblDays.setBounds(30, 170, 200, 25);
        add(lblDays);

        txtDays = new JTextField();
        txtDays.setBounds(240, 170, 150, 25);
        txtDays.setEditable(false);
        add(txtDays);

        JLabel lblTotal = new JLabel("Total Amount");
        lblTotal.setBounds(30, 210, 200, 25);
        add(lblTotal);

        txtTotal = new JTextField();
        txtTotal.setBounds(240, 210, 150, 25);
        txtTotal.setEditable(false);
        add(txtTotal);

        btnCalculate = new JButton("Calculate Total");
        btnCalculate.setBounds(30, 250, 170, 30);
        add(btnCalculate);

        btnClear = new JButton("Clear");
        btnClear.setBounds(220, 250, 170, 30);
        add(btnClear);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalView.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
